project:
  type: website
  resources:
    - keybase.txt
    - resume.pdf
    - cv/GustavoASilva_Curriculo_PTBR.pdf
    - cv/GustavoASilva_Curriculo_EN.pdf
  output-dir: docs
  
website:
  title: "Gustavo Almeida Silva"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: pacotes.qmd
        text: R Packages
      - href: consultoria.qmd
        text: Consultoria
      - href: minicurso.qmd
      - href: mat_ufjf.qmd
    tools:
      - icon: github
        href: https://github.com/Gustavo039
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2023, Gustavo Almeida Silva"

format:
  html:
    theme: [sandstone, _variables.scss]

