---
title: " "
---



# R Packages

This page contains the R packages developed during the my undergraduate period

## fableCount - Author

The fableCount R package aims to offer counting time series models for users of the fable framework. These models work within the fable framework, which provides the tools to evaluate, visualize, and combine models in a workflow consistent with the tidyverse.

* [fableCount - Official Site](https://gustavo039.github.io/fableCount/index.html)

* [fableCount - CRAN Reference](https://cran.r-project.org/web/packages/fableCount/index.html)

## Mmcsd - Coauthor

Abbreviation for Multivariate Models for Complex Survey Data. Matching longitudinal methodology models with complex sampling design. It fits fixed and random effects models and covariance structured models so far. It also provides tools to perform statistical tests considering these specifications as described in : Pacheco, P. H. (2021). "Modeling complex longitudinal data in R: development of a statistical package [https://repositorio.ufjf.br/jspui/bitstream/ufjf/13437/1/pedrohenriquedemesquitapacheco.pdf](https://repositorio.ufjf.br/jspui/bitstream/ufjf/13437/1/pedrohenriquedemesquitapacheco.pdf)

* [Mmcsd - CRAN Reference](https://cran.r-project.org/web/packages/Mmcsd/index.html)

* [Mmcsd - Official Vignette](https://cran.r-project.org/web/packages/Mmcsd/vignettes/my-vignette.pdf)

